#!/bin/bash

# This test file will be executed against an auto-generated devcontainer.json
# that includes the 'pie-extensions' Feature with no options.
#
# NOTE: pie-extensions requires composition (pie feature + PHP runtime + the
# 'extensions' option), so CI runs it via scenarios only (test-scenarios job);
# the autogenerated test would fail at install time (no pie, no extensions).

set -e

source dev-container-features-test-lib

# Feature-specific tests
check "pie installed" test -x /usr/local/bin/pie

# Report results
reportResults
